add_newline = false

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$git_branch${custom.git_status_dirty}$git_status$cmd_duration$status"""

# Timeout for commands executed by starship (in milliseconds)
command_timeout=2000

[character]
success_symbol = "[❯](cyan)[❯](blue)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](cyan)[❮](blue)"

[python]
format = '\($virtualenv\) '

[directory]
style = "green"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = '[$branch]($style)'
style = 'black'

[git_status]
format = "[($ahead_behind$stashed)]($style) "
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[custom.git_status_dirty]
when = 'string length -q -- (git status --porcelain 2>/dev/null)'
symbol = "•"
style = "white"
format="[$symbol]($style)"
shell = ["fish", "--no-config"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
